# -*- coding: utf-8 -*-
"""mergesympt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyQhoK22fohb0UalhAnCRsfUqasUSavo
"""

import pandas as pd

# Read the first CSV file with appropriate encoding
df1 = pd.read_csv("/content/drive/MyDrive/dataset.csv", encoding='latin1')

# Read the second CSV file with appropriate encoding
df2 = pd.read_csv("/content/drive/MyDrive/commonsympt.csv", encoding='latin1')

# Merge the two DataFrames based on row index
merged_df = pd.merge(df1, df2, how='outer', left_index=True, right_index=True)

# Drop duplicates based on columns Symptom_1 to Symptom_17
merged_df = merged_df.drop_duplicates(subset=merged_df.columns[1:18])

# Save the merged DataFrame to a new CSV file
merged_df.to_csv("merged_file.csv", index=False, encoding='latin1')

# Read the merged CSV file
merged_df = pd.read_csv("merged_file.csv", encoding='latin1')

# Extract the symptom columns
symptom_cols = merged_df.columns[1:18]

# Get all unique symptoms
unique_symptoms = set()
for col in symptom_cols:
  unique_symptoms.update(merged_df[col].unique())

# Create a DataFrame with unique symptoms
symptoms_df = pd.DataFrame({'Symptom': list(unique_symptoms)})

# Save the DataFrame to a new CSV file
symptoms_df.to_csv("unique_symptoms.csv", index=False, encoding='latin1')

# Read the unique symptoms CSV file
unique_symptoms_df = pd.read_csv("unique_symptoms.csv", encoding='latin1')

# Read the common symptoms CSV file
common_symptoms_df = pd.read_csv("/content/drive/MyDrive/commonsympt.csv", encoding='latin1')

# Get the unique symptoms from the unique symptoms DataFrame
unique_symptoms = set(unique_symptoms_df['Symptom'])

# Get the common symptoms from the common symptoms DataFrame
common_symptoms = set(common_symptoms_df['Symptoms'])

# Find the symptoms that are in common_symptoms but not in unique_symptoms
missing_symptoms = common_symptoms - unique_symptoms

# Append the missing symptoms to the unique symptoms DataFrame
if missing_symptoms:
  unique_symptoms_df = unique_symptoms_df.append(pd.DataFrame({'Symptom': list(missing_symptoms)}), ignore_index=True)

# Save the updated unique symptoms DataFrame to a new CSV file
unique_symptoms_df.to_csv("updated_unique_symptoms.csv", index=False, encoding='latin1')